spring:
  application:
    name: portal-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portfolio}?currentSchema=portal
    username: ${DB_USER:dev}
    password: ${DB_PASSWORD:devpass}

  jpa:
    hibernate:
      ddl-auto: validate # Flywayに任せる
    properties:
      hibernate:
        default_schema: portal

  flyway:
    enabled: true
    schemas: portal
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  private-key: classpath:keys/rsa-private.pem
  public-key: classpath:keys/rsa-public.pem
  access-token-expiration: 900000 # 15分 (ミリ秒)
  refresh-token-expiration: 2592000000 # 30日 (ミリ秒)

logging:
  level:
    com.portfolio: INFO
